// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gmr.test.proto

#ifndef PROTOBUF_gmr_2etest_2eproto__INCLUDED
#define PROTOBUF_gmr_2etest_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace gmr {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_gmr_2etest_2eproto();
void protobuf_AssignDesc_gmr_2etest_2eproto();
void protobuf_ShutdownFile_gmr_2etest_2eproto();

class test;

// ===================================================================

class test : public ::google::protobuf::Message {
 public:
  test();
  virtual ~test();
  
  test(const test& from);
  
  inline test& operator=(const test& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const test& default_instance();
  
  void Swap(test* other);
  
  // implements Message ----------------------------------------------
  
  test* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const test& from);
  void MergeFrom(const test& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);
  
  // optional string name = 2;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 2;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  
  // optional int32 scores = 3;
  inline bool has_scores() const;
  inline void clear_scores();
  static const int kScoresFieldNumber = 3;
  inline ::google::protobuf::int32 scores() const;
  inline void set_scores(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:gmr.test)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_scores();
  inline void clear_has_scores();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* name_;
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 scores_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_gmr_2etest_2eproto();
  friend void protobuf_AssignDesc_gmr_2etest_2eproto();
  friend void protobuf_ShutdownFile_gmr_2etest_2eproto();
  
  void InitAsDefaultInstance();
  static test* default_instance_;
};
// ===================================================================


// ===================================================================

// test

// optional int32 id = 1;
inline bool test::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void test::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void test::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void test::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 test::id() const {
  return id_;
}
inline void test::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}

// optional string name = 2;
inline bool test::has_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void test::set_has_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void test::clear_has_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void test::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& test::name() const {
  return *name_;
}
inline void test::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void test::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void test::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* test::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* test::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional int32 scores = 3;
inline bool test::has_scores() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void test::set_has_scores() {
  _has_bits_[0] |= 0x00000004u;
}
inline void test::clear_has_scores() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void test::clear_scores() {
  scores_ = 0;
  clear_has_scores();
}
inline ::google::protobuf::int32 test::scores() const {
  return scores_;
}
inline void test::set_scores(::google::protobuf::int32 value) {
  set_has_scores();
  scores_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace gmr

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_gmr_2etest_2eproto__INCLUDED
