/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "task.h"

bool_t
xdr_pathname (XDR *xdrs, pathname *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, 256))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_file_data (XDR *xdrs, file_data *objp)
{
	register int32_t *buf;

	 if (!xdr_bytes (xdrs, (char **)&objp->file_data_val, (u_int *) &objp->file_data_len, 4096))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_read_res (XDR *xdrs, read_res *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->ret))
		 return FALSE;
	 if (!xdr_file_data (xdrs, &objp->data))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_write_arg (XDR *xdrs, write_arg *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->fd))
		 return FALSE;
	 if (!xdr_file_data (xdrs, &objp->data))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_read_arg (XDR *xdrs, read_arg *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->fd))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->length))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_open_arg (XDR *xdrs, open_arg *objp)
{
	register int32_t *buf;

	 if (!xdr_pathname (xdrs, &objp->name))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mode))
		 return FALSE;
	return TRUE;
}
